gsap.to("#blue", { stroke: "blue", strokeWidth: 2, fill: "blue", rotate: 360, repeat: -1, transformOrigin: "50% 50%" })
gsap.to("#sunbeam", { duration: 3, stroke: "white", strokeWidth: 4, repeat: -1 })
gsap.from("#sun", { duration: 3, rotate: 360, y: 1200, ease: "elastic.out", transformOrigin: "50% 50%" })
gsap.to("#Layer-1", { position: "relative", zIndex: 0, opacity: 1 })
gsap.fromTo("#Soccer_Guy", { opacity: 0, x: -200 }, { position: "relative", duration: 2, x: 0, opacity: 1 })
gsap.fromTo("#one", { x: 330 }, { opacity: 1, duration: 2, x: 530 })
gsap.fromTo("#airball", { opacity: 0 }, { duration: 3, opacity: 1, repeat: -1 })
gsap.fromTo("#ball", { y: 590, opacity: 1 }, { duration: 3, y: 570, repeat: -1, opacity: 1 })
gsap.fromTo("#ball-lines", { y: 15, opacity: 1 }, { duration: 3, transformOrigin: "50% 50%", rotate: -360, y: -6.5, repeat: -1, opacity: 1 })
gsap.to("#Front_Leg", { duration: 3, y: -2, repeat: -1 })

let nums = gsap.timeline()

.fromTo("#num1", { y: 526 }, { duration: 1.2, y: 516, opacity: 1, ease: "bounce" }, 0)
    .fromTo("#num2", { y: 526 }, { duration: 1.5, y: 516, opacity: 1, ease: "bounce" }, .1)
    .fromTo("#num3", { y: 538 }, { duration: 2, y: 526, opacity: 1, ease: "bounce" }, .3)
    .from("#to", { x: -200 }, 0)
    .from("#love", { x: -200 }, 1)
    .from("#about", { x: -200 }, 1.5)
    .from("#our", { x: -200 }, 1.7)
    .from("#city", { duration: 1, x: -200, ease: "bounce" }, 2)
    .to("#people", { rotate: 360, transformOrigin: "50% 50%" })
    .from("#places", { y: 100, transformOrigin: "50% 50%" })
    .from("#things", { duration: 1, opacity: 0, x: 400, rotate: 360, transformOrigin: "50% 50%" })